"""Build the policy directory the browser suite's API runs against.

**Why this exists.** The sign-in limit (`throttle.auth.per_minute`, B6) counts
per caller, and every request the browser suite makes comes from one address,
127.0.0.1. Ten sign-ins a minute is right for one person and far too few for
forty specs that each need a session, so the suite failed on 429s that had
nothing to do with what it tests.

The fix is a policy value, not a code path (I10): this copies `config/policy`
and raises that one key to its guardrail maximum, so the limiter still runs
and is still resolved from the policy store, just with a ceiling the suite
cannot reach by accident. The committed policy is never changed, and only
`make dev-e2e` points `CLARITY_POLICY_DIR` at the copy.

Usage: ``python scripts/e2e_policy.py <source dir> <target dir>``
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

import yaml

#: Raised for the suite only. Each is set to its guardrail maximum.
RAISED = ("throttle.auth.per_minute",)


def build(source: Path, target: Path) -> None:
    if target.exists():
        shutil.rmtree(target)
    shutil.copytree(source, target)

    throttle = target / "throttle.yaml"
    document = yaml.safe_load(throttle.read_text(encoding="utf-8"))
    for key in document["keys"]:
        if key["key"] in RAISED:
            ceiling = str(key["guardrail"]["max"])
            for value in key["values"]:
                value["value"] = ceiling
    throttle.write_text(
        "# Generated by scripts/e2e_policy.py for the browser suite only.\n"
        + yaml.safe_dump(document, sort_keys=False),
        encoding="utf-8",
    )


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    build(Path(sys.argv[1]), Path(sys.argv[2]))
